---
sidebar: sidebar 
permalink: migration/migrate-vms-to-ec2-fsxn-overview.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: 'Este relatório técnico aborda como migrar VMs VMware vSphere locais para uma instância do Amazon EC2 com discos de dados colocados em LUNs iSCSI FSx ONTAP usando a funcionalidade "mobilidade de dados como código" do MigrateOps do Cirrus Migrate Cloud (CMC).' 
---
= Saiba mais sobre a migração de VMs para o Amazon EC2 usando o Amazon FSx para ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Amazon FSx for NetApp ONTAP facilita a migração de VMs do VMware vSphere para o Amazon EC2, preservando recursos importantes de armazenamento, como snapshots, provisionamento fino e replicação.  Ele suporta ferramentas e protocolos familiares, simplificando o processo de migração e reduzindo custos e complexidade.

As organizações estão acelerando suas migrações para soluções de computação em nuvem na AWS, aproveitando serviços como instâncias do Amazon Elastic Compute Cloud (Amazon EC2) e Amazon FSx for NetApp ONTAP (FSx ONTAP) para modernizar suas infraestruturas de TI, obter economia de custos e melhorar a eficiência operacional.  Essas ofertas da AWS permitem migrações que otimizam o custo total de propriedade (TCO) por meio de modelos de preços baseados no consumo e recursos de armazenamento empresarial, fornecendo a flexibilidade e a escalabilidade para atender às crescentes demandas de negócios globais.



== Visão geral

Para empresas profundamente investidas no VMware vSphere, migrar para a AWS é uma opção econômica, dadas as condições atuais do mercado, o que representa uma oportunidade única.

À medida que essas organizações fazem a transição para a AWS, elas buscam capitalizar a agilidade e os benefícios de custo da nuvem, preservando conjuntos de recursos familiares, principalmente quando se trata de armazenamento.  Manter operações contínuas com protocolos de armazenamento familiares — especialmente iSCSI — processos, ferramentas e conjuntos de habilidades é crucial ao migrar cargas de trabalho ou configurar soluções de recuperação de desastres.

Usando o serviço de armazenamento gerenciado da AWS FSx ONTAP para reter os recursos de armazenamento empresarial, também provenientes de armazenamento de terceiros no local, as empresas podem liberar o poder da AWS, minimizando interrupções e maximizando seus investimentos futuros.

Este relatório técnico aborda como migrar VMs VMware vSphere locais para uma instância do Amazon EC2 com discos de dados colocados em LUNs iSCSI FSx ONTAP usando a funcionalidade "mobilidade de dados como código" do MigrateOps do Cirrus Migrate Cloud (CMC).



== Requisitos da solução

Há uma série de desafios que os clientes da VMware estão tentando resolver atualmente.  Essas organizações querem:

. Aproveite os recursos de armazenamento empresarial, como provisionamento fino, tecnologias de eficiência de armazenamento, clones de pegada zero, backups integrados, replicação em nível de bloco e camadas.  Isso ajuda a otimizar os esforços de migração e a implantação à prova do futuro na AWS desde o primeiro dia.
. Otimize as implantações de armazenamento atualmente na AWS que usam instâncias do Amazon EC2 incorporando o FSx ONTAP e os recursos de otimização de custos que ele fornece.
. Reduza o custo total de propriedade (TCO) do uso de instâncias do Amazon EC2 com soluções de armazenamento em bloco, dimensionando corretamente as instâncias do Amazon EC2 para atender aos parâmetros de IOPS e taxa de transferência necessários.  Com o armazenamento em bloco, as operações de disco do Amazon EC2 têm um limite de largura de banda e taxas de E/S.  O armazenamento de arquivos com o FSx ONTAP usa largura de banda de rede.  Em outras palavras, o FSx ONTAP não tem limites de E/S em nível de VM.




== Visão geral dos componentes técnicos



=== Conceitos do FSx ONTAP

O Amazon FSx ONTAP é um serviço de armazenamento da AWS totalmente gerenciado que fornece aos sistemas de arquivos NetApp ONTAP todos os recursos, desempenho e APIs familiares de gerenciamento de dados ONTAP na AWS.  Seu armazenamento de alto desempenho suporta vários protocolos (NFS, SMB, iSCSI), fornecendo um único serviço para cargas de trabalho que usam instâncias EC2 do Windows, Linux e macOS.

Como o FSx ONTAP é um sistema de arquivos ONTAP , ele traz consigo uma série de recursos e serviços familiares do NetApp , incluindo tecnologia de replicação de dados SnapMirror , clones finos e cópias do NetApp Snapshot.  Ao aproveitar uma camada de capacidade de baixo custo por meio de hierarquização de dados, o FSx ONTAP é elástico e pode atingir uma escala praticamente ilimitada.  Além disso, com a tecnologia de eficiência de armazenamento exclusiva da NetApp , os custos de armazenamento na AWS são ainda mais reduzidos.  Para mais informações, vejalink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introdução ao Amazon FSx ONTAP"] .



==== Sistema de arquivos

O recurso central do FSx ONTAP é seu sistema de arquivos baseado em armazenamento em unidade de estado sólido (SSD).  Ao provisionar um sistema de arquivos FSx ONTAP , o usuário insere a taxa de transferência e a capacidade de armazenamento desejadas e seleciona uma Amazon VPC onde o sistema de arquivos residirá.

Os usuários também podem escolher entre dois modelos de implantação de alta disponibilidade integrados para o sistema de arquivos: implantação de Zona de Multidisponibilidade (AZ) ou de AZ única.  Cada uma dessas opções oferece seu próprio nível de durabilidade e disponibilidade, que os clientes podem selecionar dependendo dos requisitos de continuidade de negócios do seu caso de uso.  Implantações Multi-AZ consistem em nós duplos que se replicam perfeitamente em duas AZs.  A opção de implantação de AZ única, mais otimizada em termos de custo, estrutura o sistema de arquivos em dois nós divididos entre dois domínios de falha separados, ambos residindo em uma única AZ.



=== Máquinas Virtuais de Armazenamento

Os dados no sistema de arquivos FSx ONTAP são acessados por meio de uma partição de armazenamento lógica chamada máquina virtual de armazenamento (SVM).  Um SVM é, na verdade, seu próprio servidor de arquivos equipado com seus próprios dados e pontos de acesso administrativo.  Ao acessar LUNs iSCSI em um sistema de arquivos FSx ONTAP , a instância do Amazon EC2 faz interface diretamente com o SVM usando o endereço IP do ponto de extremidade iSCSI do SVM.

Embora seja possível manter uma única SVM em um cluster, a opção de executar várias SVMs em um cluster tem uma ampla gama de usos e benefícios.  Os clientes podem determinar o número ideal de SVMs a serem configurados considerando suas necessidades comerciais, incluindo seus requisitos de isolamento de carga de trabalho.



==== Volumes

Os dados dentro de um FSx ONTAP SVM são armazenados e organizados em estruturas conhecidas como volumes, que atuam como contêineres virtuais.  Um volume individual pode ser configurado com um ou vários LUNs.  Os dados armazenados em cada volume consomem capacidade de armazenamento no sistema de arquivos.  No entanto, como o FSx ONTAP provisiona o volume de forma enxuta, o volume só ocupa capacidade de armazenamento para a quantidade de dados que estão sendo armazenados.



=== O conceito Cirrus Migrate Cloud MigrateOps

CMC é uma oferta de software como serviço (SaaS) transacionável da Cirrus Data Solutions, Inc. que está disponível no AWS Marketplace.  MigrateOps é um recurso de automação de mobilidade de dados como código do CMC que permite que você gerencie declarativamente suas operações de mobilidade de dados em escala usando configurações de operação simples em YAML.  Uma configuração do MigrateOps determina como você deseja que suas tarefas de mobilidade de dados sejam executadas.  Para saber mais sobre o MigrateOps, consultelink:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["Sobre o MigrateOps"] .

O MigrateOps adota uma abordagem que prioriza a automação, criada especificamente para otimizar todo o processo, garantindo mobilidade de dados empresariais em escala de nuvem sem interrupções operacionais.  Além das funcionalidades já ricas em recursos que o CMC oferece para automação, o MigrateOps adiciona outras automações que geralmente são gerenciadas externamente, como:

* Remediação do sistema operacional
* Corte de aplicação e agendamento de aprovação
* Migração de cluster com tempo de inatividade zero
* Integração de plataforma de nuvem pública/privada
* Integração de plataforma de virtualização
* Integração de gerenciamento de armazenamento empresarial
* Configuração SAN (iSCSI)


Com as tarefas acima totalmente automatizadas, todas as etapas tediosas na preparação da VM de origem local (como adicionar agentes e ferramentas da AWS), criação de LUNs FSx de destino, configuração de iSCSI e Multipath/MPIO na instância de destino da AWS e todas as tarefas de interromper/iniciar serviços de aplicativos são eliminadas simplesmente especificando parâmetros em um arquivo YAML.

O FSx ONTAP é usado para fornecer LUNs de dados e dimensionar corretamente o tipo de instância do Amazon EC2, ao mesmo tempo em que fornece todos os recursos que as organizações tinham anteriormente em seus ambientes locais.  O recurso MigrateOps do CMC será usado para automatizar todas as etapas envolvidas, incluindo o provisionamento de LUNs iSCSI mapeados, transformando isso em uma operação previsível e declarativa.

*Observação*: o CMC exige que um agente muito fino seja instalado nas instâncias da máquina virtual de origem e destino para garantir a transferência segura de dados do armazenamento de origem para o FSx ONTAP.



== Benefícios do uso do Amazon FSx ONTAP com instâncias EC2

O armazenamento FSx ONTAP para instâncias do Amazon EC2 oferece vários benefícios:

* Armazenamento de alto rendimento e baixa latência que fornecem alto desempenho consistente para as cargas de trabalho mais exigentes
* O cache NVMe inteligente melhora o desempenho
* Capacidade, rendimento e IOPs ajustáveis podem ser alterados rapidamente e se adaptar rapidamente às mudanças nas demandas de armazenamento
* Replicação de dados baseada em bloco do armazenamento ONTAP local para a AWS
* Acessibilidade multiprotocolo, incluindo para iSCSI, amplamente utilizado em implantações VMware locais
* A tecnologia NetApp Snapshot e DR orquestrada pelo SnapMirror evitam a perda de dados e aceleram a recuperação
* Recursos de eficiência de armazenamento que reduzem o espaço ocupado e os custos de armazenamento, incluindo provisionamento fino, desduplicação de dados, compactação e compactação
* A replicação eficiente reduz o tempo de criação de backups de horas para apenas minutos, otimizando o RTO
* Opções granulares para backup e restauração de arquivos usando o NetApp SnapCenter


A implantação de instâncias do Amazon EC2 com o FSx ONTAP como camada de armazenamento baseada em iSCSI oferece recursos de gerenciamento de dados de missão crítica de alto desempenho e recursos de eficiência de armazenamento que reduzem custos e podem transformar sua implantação na AWS.

Executando um Flash Cache, várias sessões iSCSI e aproveitando um tamanho de conjunto de trabalho de 5%, é possível que o FSx ONTAP forneça IOPS de ~350K, fornecendo níveis de desempenho para atender até mesmo às cargas de trabalho mais intensivas.

Como apenas limites de largura de banda de rede são aplicados ao FSx ONTAP, e não limites de largura de banda de armazenamento em bloco, os usuários podem aproveitar pequenos tipos de instâncias do Amazon EC2 e, ao mesmo tempo, obter as mesmas taxas de desempenho de tipos de instâncias muito maiores.  Usar esses tipos de instâncias pequenas também mantém os custos de computação baixos, otimizando o TCO.

A capacidade do FSx ONTAP de atender a vários protocolos é outra vantagem que ajuda a padronizar um único serviço de armazenamento da AWS para uma ampla gama de requisitos de serviços de dados e arquivos existentes.  Para empresas profundamente investidas no VMware vSphere, migrar para a AWS é uma opção econômica, dadas as condições atuais do mercado, o que representa uma oportunidade única.
