---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: 'Provisione armazenamento ONTAP para o ambiente virtual Proxmox (VE) usando protocolos NAS (NFS, SMB) e protocolos SAN (FC, iSCSI, NVMe). Selecione o procedimento específico do protocolo apropriado para configurar o armazenamento compartilhado do seu cluster Proxmox VE.' 
---
= Saiba mais sobre protocolos de armazenamento para Proxmox VE com NetApp ONTAP.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Provisione armazenamento ONTAP para o ambiente virtual Proxmox (VE) usando protocolos NAS (NFS, SMB) e protocolos SAN (FC, iSCSI, NVMe). Selecione o procedimento específico do protocolo apropriado para configurar o armazenamento compartilhado do seu cluster Proxmox VE.

Certifique-se de que os hosts Proxmox VE tenham interfaces FC, Ethernet ou outras interfaces suportadas conectadas por cabo aos switches que se comunicam com as interfaces lógicas do ONTAP . Sempre verifique o https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de Interoperabilidade"] para configurações suportadas. Os cenários de exemplo são criados partindo do pressuposto de que duas placas de interface de rede de alta velocidade estão disponíveis em cada host Proxmox VE e são conectadas entre si para criar interfaces agregadas (bonded interfaces) para tolerância a falhas e melhor desempenho. As mesmas conexões de uplink são usadas para todo o tráfego de rede, incluindo gerenciamento de hosts, tráfego de máquinas virtuais/contêineres e acesso ao armazenamento. Quando houver mais interfaces de rede disponíveis, considere separar o tráfego de armazenamento de outros tipos de tráfego.

Para obter informações sobre a arquitetura de armazenamento ONTAP e os tipos de armazenamento suportados, consulte link:proxmox-ontap-architecture.html["Saiba mais sobre a arquitetura de armazenamento ONTAP para Proxmox VE."] e link:proxmox-storage-types.html["Saiba mais sobre os tipos de armazenamento suportados pelo Proxmox VE."].


NOTE: Ao usar LVM com protocolos SAN (FC, iSCSI, NVMe-oF), o grupo de volumes pode conter vários LUNs ou namespaces NVMe. Nesse caso, todos os LUNs ou namespaces devem fazer parte do mesmo grupo de consistência para garantir a integridade dos dados. Não oferecemos suporte a grupos de volumes que abranjam várias SVMs do ONTAP . Cada grupo de volumes deve ser criado a partir de LUNs ou namespaces da mesma SVM.



== Escolha um protocolo de armazenamento

Selecione o protocolo que melhor se adequa ao seu ambiente e às suas necessidades:

* link:proxmox-ontap-smb.html["Configurar armazenamento SMB/CIFS"] - Configure compartilhamentos de arquivos SMB/CIFS para Proxmox VE com suporte multicanal para tolerância a falhas e desempenho aprimorado em várias conexões de rede.
* link:proxmox-ontap-nfs.html["Configurar armazenamento NFS"] - Configure o armazenamento NFS para Proxmox VE com nConnect ou trunking de sessão para tolerância a falhas e melhorias de desempenho usando várias conexões de rede.
* link:proxmox-ontap-fc.html["Configure o LVM com FC"] - Configure o Logical Volume Manager (LVM) com Fibre Channel para acesso ao armazenamento em blocos de alto desempenho e baixa latência em hosts Proxmox VE.
* link:proxmox-ontap-iscsi.html["Configurar LVM com iSCSI"] - Configure o Logical Volume Manager (LVM) com iSCSI para acesso ao armazenamento em bloco em redes Ethernet padrão com suporte a múltiplos caminhos.
* link:proxmox-ontap-nvme-fc.html["Configure o LVM com NVMe/FC"] - Configure o Logical Volume Manager (LVM) com NVMe sobre Fibre Channel para armazenamento em bloco de alto desempenho usando o protocolo NVMe moderno.
* link:proxmox-ontap-nvme-tcp.html["Configurar LVM com NVMe/TCP"] - Configure o Logical Volume Manager (LVM) com NVMe sobre TCP para armazenamento em bloco de alto desempenho em redes Ethernet padrão usando o protocolo NVMe moderno.

