---
sidebar: sidebar 
permalink: vmware/vmw-vcf-disaster-recovery.html 
keywords: vmware, vcf, dr, disaster recovery, draas, bluexp 
summary:  
---
= Saiba mais sobre como proteger os datastores VMware usando a BlueXP disaster recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre as soluções da NetApp para recuperação de desastres usando a BlueXP disaster recovery para VMware.  Isso fornece soluções robustas para recuperação de desastres usando replicação em nível de bloco de um site primário para um site de recuperação de desastres.

O BlueXP DRaaS é um método eficaz e econômico para proteger cargas de trabalho contra falhas de site e problemas de integridade de dados, incluindo ataques de ransomware.  Além disso, o NetApp BlueXP DRaaS aprimora essa estratégia ao fornecer uma solução de recuperação de desastres gerenciada e baseada em nuvem, garantindo recuperação rápida e tempo de inatividade mínimo durante desastres.

Consulte as soluções a seguir para obter detalhes técnicos.

* link:vmw-disaster-recovery-vmfs.html["DR usando BlueXP DRaaS para datastores VMFS"]
* link:vmw-disaster-recovery-nfs.html["DR usando BlueXP DRaaS para datastores NFS"]

