---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= Aprenda a gerenciar máquinas virtuais usando ONTAP tools for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
As ONTAP tools for VMware vSphere simplificam o gerenciamento de ciclo de vida de VMs usando o storage da NetApp. Os administradores podem gerenciar o storage diretamente do vCenter Server, simplificando as operações e aumentando a escalabilidade. Componentes principais, como o vSphere Client plug-in, o VASA Provider e o Storage Replication Adapter (SRA), otimizam o provisionamento, o monitoramento de desempenho e a recuperação de desastres.



[[introduction]]
== Introdução

Ele permite que os administradores gerenciem o armazenamento diretamente no vCenter Server e simplifiquem o armazenamento e o gerenciamento de dados para ambientes VMware.  A ferramenta de plug-in VMware vSphere Client foi projetada para integrar a funcionalidade de plug-in ao vSphere Client sem a necessidade de execução dentro do vCenter Server.  Isso fornece isolamento de plug-in e permite o dimensionamento horizontal de plug-ins que operam em grandes ambientes vSphere.



[[ontap-tools-components]]
== Componentes das ferramentas ONTAP

* *vSphere Client plug-in* O plug-in inclui a interface integrada ao cliente vSphere, na qual você pode adicionar controladores de armazenamento, provisionar datastores, monitorar o desempenho dos datastores e exibir e atualizar as configurações do host ESXi. No ONTAP tools 9.x, esse componente é chamado de o Virtual Storage Console (VSC).
* *Provedor VASA* O provedor VMware vSphere APIs for Storage Awareness (VASA) para ONTAP envia informações sobre o armazenamento usado pelo VMware vSphere para o vCenter Server, permitindo o provisionamento de armazenamentos de dados VMware Virtual Volumes (vVols), criação e uso de perfis de capacidade de armazenamento, verificação de conformidade e monitoramento de desempenho.
* *Adaptador de Replicação de Armazenamento (SRA)* Quando habilitado e usado com o VMware Site Recovery Manager (SRM), o SRA facilita a recuperação de datastores e máquinas virtuais do vCenter Server em caso de falha, permitindo a configuração de sites protegidos e sites de recuperação para recuperação de desastres.


Para obter mais informações, consulte a documentação do ONTAP tools for VMware vSphere para a sua versão:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Documentação do ONTAP tools for VMware vSphere 10.x"^] (última versão)
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Documentação do ONTAP tools for VMware vSphere 9.x"^]

