---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= Use um armazenamento de dados NFS no ONTAP como armazenamento principal para o domínio de gerenciamento VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Neste caso de uso, descrevemos o procedimento para usar um armazenamento de dados NFS existente no ONTAP como armazenamento primário para domínios de gerenciamento do VMware Cloud Foundation (VCF).  Este procedimento resume os componentes necessários, as etapas de configuração e o processo de implantação.



== Introdução

Quando apropriado, faremos referência à documentação externa para as etapas que devem ser executadas no SDDC Manager do VCF e faremos referência às etapas específicas da parte de configuração de armazenamento.

Para obter informações sobre como converter um ambiente vSphere baseado em NFS existente com ONTAP, consultelink:vmw-vcf-mgmt-nfs.html["Converter ambiente vSphere (armazenamento de dados NFS) em domínio de gerenciamento VCF"] .


NOTE: A versão 5.2 do VCF introduziu a capacidade de converter um ambiente vSphere 8 existente em um domínio de gerenciamento VCF ou importar como domínios de carga de trabalho VCF VI.  Antes desta versão, o VMware vSAN era a única opção de armazenamento principal para o domínio de gerenciamento do VCF.


NOTE: Esta solução é aplicável para plataformas ONTAP que suportam armazenamento NFS, incluindo NetApp AFF e FAS.



== Pré-requisitos

Os seguintes componentes e configurações são usados neste cenário:

* Sistema de armazenamento NetApp com uma máquina virtual de armazenamento (SVM) configurada para permitir tráfego NFS.
* A interface lógica (LIF) foi criada na rede IP que transportará o tráfego NFS e está associada ao SVM.
* Um cluster vSphere 8 com 4 hosts ESXi e um dispositivo vCenter colocalizados no cluster.
* Grupo de portas distribuídas configurado para tráfego de armazenamento vMotion e NFS nas VLANs ou segmentos de rede estabelecidos para essa finalidade.
* Baixe o software necessário para a conversão de VCF.


Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consultelink:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["Documentação do VMware Cloud Foundation"] .



== Etapas de implantação



=== Domínio de Gerenciamento - Cluster Padrão

O armazenamento principal do NFS no cluster inicial só é suportado com a ferramenta de importação brownfield do VCF.  Se o VCF for implantado com a ferramenta Cloud Builder (até a versão 5.2.x), somente o VSAN será suportado.

Para obter mais informações sobre como usar um ambiente vSphere existente, consulte https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["convertendo o ambiente vSphere existente para o domínio de gerenciamento"] para mais informações.



=== Domínio de Gerenciamento - Cluster Adicional

O cluster vSphere adicional no domínio de gerenciamento pode ser implantado com as seguintes opções:

* Tenha um cluster adicional no ambiente vSphere e use a ferramenta de importação brownfield do VCF para converter o ambiente vSphere em domínio de gerenciamento. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["ONTAP tools for VMware vSphere"] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Gerenciador de sistema ou API ONTAP"] pode ser usado para implantar o armazenamento de dados NFS no cluster vSphere.
* Use a API do SDDC para implantar um cluster adicional.  Os hosts do vSphere devem ter o armazenamento de dados NFS configurado.  Usar https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Gerenciador de sistema ou API ONTAP"] para implantar LUN em hosts vSphere.
* Use a interface de usuário do SDDC Manager para implantar um cluster adicional.  Mas essa opção só cria um armazenamento de dados vSAN com versões anteriores à 5.2.x.




== Informações adicionais

Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consultelink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentação do VMware Cloud Foundation"] .
