---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Use um armazenamento de dados VMFS baseado em FC no ONTAP como armazenamento principal para o domínio de gerenciamento VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Neste caso de uso, descrevemos o procedimento para criar um datastore VMFS baseado em FC no ONTAP como o storage primário para o domínio de gerenciamento do VMware Cloud Foundation (VCF). Este procedimento resume os componentes, configurações e etapas de implantação necessários.



[[introduction]]
== Introdução

Quando apropriado, faremos referência à documentação externa para os passos que devem ser executados em vCenter e mencionaremos os passos que são específicos para a parte de configuração de storage.

Para obter informações sobre como converter um datastore VMFS existente (incluindo iSCSI e NVMe-oF) no ambiente vSphere com o ONTAP, consulte link:vmw-vcf-mgmt-vmfs.html["Convergir o ambiente vSphere (datastore VMFS) para o domínio de gerenciamento VCF"].


NOTE: A versão 5.2 do VCF introduziu a capacidade de converter um ambiente vSphere 8 existente em um domínio de gerenciamento do VCF ou importá-lo como domínios de carga de trabalho do VCF VI. Antes dessa versão, o VMware vSAN era a única opção de storage primário para o domínio de gerenciamento do VCF. É recomendável implantar as VMs do controlador NSX em um datastore VMFS baseado em FC ou usar dois switches de rede para evitar ponto único de falha. Se essas opções não estiverem disponíveis, considere usar o vSAN para hospedar essas VMs.


NOTE: Esta solução é aplicável para plataformas ONTAP que suportam armazenamento FC, incluindo NetApp ASA, AFF e FAS.



[[prerequisites]]
== Pré-requisitos

Os seguintes componentes e configurações são usados neste cenário:

* Sistema de armazenamento NetApp com uma máquina virtual de armazenamento (SVM) configurada para permitir tráfego FC.
* Interfaces lógicas (LIF) foram criadas na estrutura FC que transportará o tráfego FC e está associada ao SVM.
* O zoneamento foi configurado para usar zoneamento de iniciador-destino único em switches FC para HBAs de host e destinos de armazenamento.


Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consulte link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentação do VMware Cloud Foundation"].



[[deployment-steps]]
== Etapas de implantação



[[management-domain-default-cluster]]
=== Domínio de Gerenciamento - Cluster Padrão

A ferramenta VCF Installer oferece suporte a VMFS em datastores FC, NFS v3 e vSAN para o domínio de gerenciamento. As etapas a seguir descrevem o procedimento para implantar um domínio de gerenciamento com um datastore VMFS baseado em FC no ONTAP como o storage primário.

Para obter mais informações sobre como usar um ambiente vSphere existente, consulte link:vmw-vcf-mgmt-vmfs.html["Convergir o ambiente vSphere (datastore VMFS) para o domínio de gerenciamento VCF"].



[[management-domain-additional-cluster]]
=== Domínio de Gerenciamento - Cluster Adicional

Para expandir o domínio de gerenciamento com um cluster adicional, consulte  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Adicionar um cluster SDDC a um domínio VCF"].

Em um nível mais alto, as etapas para adicionar um cluster adicional ao domínio de gerenciamento são as seguintes: * Certifique-se de que os hosts estejam comissionados e os pools de rede estejam configurados no vCenter. * O LUN é provisionado no sistema de storage ONTAP e apresentado aos hosts no cluster adicional. * Crie um novo cluster SDDC no domínio de gerenciamento no vCenter e siga o assistente para adicionar o cluster adicional ao domínio de gerenciamento.



[[additional-information]]
== Informações adicionais

Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consulte link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentação do VMware Cloud Foundation"].
