---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: Analise os requisitos para convergir um cluster vSphere com datastores NFS do NetApp ONTAP para um domínio de gerenciamento do VMware Cloud Foundation. 
---
= Requisitos de implantação para convergir a instância do servidor vCenter para o domínio de gerenciamento do VCF usando datastores NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Analise os requisitos para convergir um cluster vSphere com datastores NFS do NetApp ONTAP para um domínio de gerenciamento do VMware Cloud Foundation.

O processo de convergência requer um sistema de storage AFF ou AFX, SVMs e LIFs para tráfego NFS, VLANs NFS em switches, um cluster vSphere com hosts vSphere e vCenter, e um segmento de rede dedicado para vMotion.



[[infrastructure-requirements]]
== Requisitos de infraestrutura

Certifique-se de que os seguintes componentes e configurações estejam instalados.

* NetApp AFF ou AFX sistema de storage com uma máquina virtual de storage (SVM) configurada para permitir tráfego NFS.
* Interface lógica (LIF) criada na rede IP para transportar tráfego NFS e associada ao SVM.
* Um cluster vSphere com pelo menos 2 hosts vSphere e um appliance vCenter co-localizado no cluster.
* Grupo de portas distribuídas configurado para tráfego de armazenamento vMotion e NFS nas VLANs ou segmentos de rede estabelecidos para essa finalidade.
* Ferramenta de instalação do VCF para convergir o vCenter ao domínio de gerenciamento do VCF.
* Pré-requisitos para ferramentas ONTAP .
+
Para obter informações completas sobre os pré-requisitos para ferramentas ONTAP , consulte https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["Pré-requisitos para ONTAP tools for VMware vSphere"] .

+
As ONTAP tools for VMware vSphere podem ser instaladas em configurações HA ou não HA.





[[additional-resources]]
== Recursos adicionais

* Para obter informações sobre storage compatível e outras considerações para convergir vSphere para VCF, consulte  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["Configurações suportadas e não suportadas para convergência com o VCF"].
* Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] .
* Para obter informações sobre como configurar o VCF, consulte o link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentação do VMware Cloud Foundation 9.1"].




[[whats-next]]
== O que vem a seguir?

Depois de revisar os requisitos de implantação,link:vmw-vcf-mgmt-nfs-deploy.html["implantar ferramentas ONTAP e provisionar o armazenamento de dados NFS"] .
