---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Utilize um datastore VMFS baseado em FC no ONTAP como storage primário para um domínio de workload VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Neste caso de uso, descrevemos o procedimento para configurar um datastore VMFS Fibre Channel (FC) no ONTAP como o storage primário para um domínio de carga de trabalho do VMware Cloud Foundation (VCF). Este procedimento resume os componentes necessários, as etapas de configuração e o processo de implantação.



[[benefits-of-fibre-channel]]
== Benefícios do Fibre Channel

*Alto desempenho:* o FC fornece altas taxas de transferência de dados, tornando-o ideal para aplicações que exigem acesso rápido e confiável a grandes quantidades de dados.

*Baixa latência:* latência muito baixa, o que é crucial para aplicativos sensíveis ao desempenho, como bancos de dados e ambientes virtualizados.

*Confiabilidade:* As redes FC são conhecidas por sua robustez e confiabilidade, com recursos como redundância integrada e correção de erros.

*Largura de banda dedicada:* o FC fornece largura de banda dedicada para tráfego de armazenamento, reduzindo o risco de congestionamento da rede.

Para obter mais informações sobre o uso do Fibre Channel com sistemas de armazenamento NetApp , consulte https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisionamento SAN com FC"] .



[[scenario-overview]]
== Visão geral do cenário

Este cenário abrange as seguintes etapas de alto nível:

* Crie uma máquina virtual de armazenamento (SVM) com interfaces lógicas (LIFs) para tráfego FC.
* Colete informações WWPN dos hosts a serem implantados e crie grupos iniciadores correspondentes no sistema de armazenamento ONTAP .
* Crie um volume FC no sistema de armazenamento ONTAP .
* Mapeie grupos iniciadores para o volume FC criado.
* Utilize zoneamento de iniciador-alvo único em switches FC.  Crie uma zona para cada iniciador (zona de iniciador único).
+
** Para cada zona, inclua um destino que seja a interface lógica ONTAP FC (WWPN) para as SVMs.  Deve haver pelo menos duas interfaces lógicas por nó por SVM.  Não utilize o WWPN das portas físicas.


* Crie um pool de rede para o tráfego de vMotion em vCenter.
* Comissione hosts no vCenter para uso em um Domínio de Carga de Trabalho.
* Implemente um domínio de carga de trabalho no VCF Ops usando um datastore VMFS em FC como storage primário.



NOTE: Esta solução é aplicável para plataformas ONTAP que suportam storage FC, incluindo NetApp ASAr2, AFF e FAS.



[[prerequisites]]
== Pré-requisitos

Os seguintes componentes e configurações são usados neste cenário:

* Um sistema de storage ONTAP AFF, ASA ou FAS com portas FC conectadas a switches FC.
* SVM criado com FC lifs.
* vSphere com HBAs FC conectados a switches FC.
* O zoneamento de iniciador-alvo único é configurado em switches FC.
* Certifique-se de que a política de multipathing do SVM esteja definida como ativo-ativo.



NOTE: A NetApp recomenda vários caminhos para LUNs FC.



[[deployment-steps]]
== Etapas de implantação



[[vcf-workload-domain-default-cluster]]
=== Domínio de workload VCF - cluster padrão

Após o domínio de gerenciamento estar configurado e em funcionamento, o domínio de workload do VCF pode ser criado:

* Utilizando a interface de usuário VCF Ops. Os hosts vSphere são comissionados no vCenter e o pool de rede é configurado. Use o System Manager ou a API ONTAP para implantar LUN no hosts vSphere.
* Importe um ambiente vSphere existente como novo domínio de carga de trabalho. O ONTAP tools for VMware vSphere, o System Manager ou a ONTAP API podem ser usados para implantar o datastore VMFS no cluster vSphere.




[[vcf-workload-domain-additional-cluster]]
=== Domínio de workload VCF - cluster adicional

Para expandir o domínio de carga de trabalho com um cluster adicional, consulte  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Adicionar um cluster SDDC a um domínio VCF"].

Em linhas gerais, os passos para adicionar um cluster adicional ao domínio de carga de trabalho são os seguintes: * Certifique-se de que os hosts estejam comissionados e os pools de rede estejam configurados no vCenter. * O LUN deve ser provisionado no sistema de storage ONTAP e apresentado aos hosts no cluster adicional. * Crie um novo cluster SDDC no domínio de carga de trabalho no vCenter e siga o assistente para adicionar o cluster adicional ao domínio de carga de trabalho.



[[additional-information]]
== Informações adicionais

Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consulte link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentação do VMware Cloud Foundation"].
