---
sidebar: sidebar 
permalink: vmware/vmw-demos-videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: Esta página fornece uma introdução a vídeos e tutoriais. 
---
= Assista a vídeos e demonstrações sobre virtualização com a NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Assista a vídeos e demonstrações que explicam recursos importantes de soluções de nuvem híbrida, virtualização e contêineres.  Veja como usar as ferramentas NetApp ONTAP tools for VMware vSphere, o SnapCenter Plug-in for VMware vSphere, a proteção de dados 3-2-1 e como o NetApp funciona com AWS e Azure.  Obtenha dicas úteis para configurar e gerenciar essas tecnologias.

.Ferramentas NetApp ONTAP para VMware vSphere
[%collapsible%open]
====
.Ferramentas ONTAP para VMware - Visão geral
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.Provisionamento de armazenamento de dados VMware iSCSI com ONTAP
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.Provisionamento de armazenamento de dados VMware NFS com ONTAP
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.SnapCenter Plug-in for VMware vSphere
[%collapsible%open]
====
O software NetApp SnapCenter software é uma plataforma empresarial fácil de usar para coordenar e gerenciar com segurança a proteção de dados em aplicativos, bancos de dados e sistemas de arquivos.

O SnapCenter Plug-in for VMware vSphere permite que você execute operações de backup, restauração e anexação para VMs, além de operações de backup e montagem para armazenamentos de dados registrados no SnapCenter diretamente no VMware vCenter.

Para obter mais informações sobre o NetApp SnapCenter Plug-in for VMware vSphere, consulte olink:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Visão geral do SnapCenter Plug-in for VMware vSphere-in NetApp SnapCenter para VMware vSphere"] .

.SnapCenter Plug-in for VMware vSphere - Pré-requisitos da solução
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Implantação
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Fluxo de trabalho de backup
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Fluxo de trabalho de restauração
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - Fluxo de trabalho de restauração de SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.Soluções de proteção de dados 3-2-1
[%collapsible%open]
====
As soluções de proteção de dados 3-2-1 combinam backups primários e secundários locais, usando a tecnologia SnapMirror , com cópias replicadas para armazenamento de objetos usando BlueXP backup and recovery.

.Proteção de dados 3-2-1 para datastores VMFS com SnapCenter Plug-in for VMware vSphere e backup e recuperação BlueXP para máquinas virtuais
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.VMware Cloud na AWS com AWS FSx ONTAP
[%collapsible%open]
====
.Armazenamento conectado de convidado do Windows com FSx ONTAP usando iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Armazenamento conectado para convidados Linux com FSx ONTAP usando NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Economia de TCO do VMware Cloud na AWS com o Amazon FSx ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Armazenamento de dados suplementar do VMware Cloud on AWS com Amazon FSx ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.Implantação e configuração do VMware HCX para VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Demonstração de migração do vMotion com VMware HCX para VMC e FSx ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Demonstração de migração a frio com VMware HCX para VMC e FSx ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Serviços VMware do Azure no Azure com Azure NetApp Files (ANF)
[%collapsible%open]
====
.Visão geral do armazenamento de dados suplementar da solução VMware do Azure com o Azure NetApp Files
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Solução Azure VMware DR com Cloud Volumes ONTAP, SnapCenter e JetStream
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.Demonstração de migração a frio com VMware HCX para AVS e ANF
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.Demonstração do vMotion com VMware HCX para AVS e ANF
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.Demonstração de migração em massa com VMware HCX para AVS e ANF
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware Cloud Foundation com NetApp ONTAP
[%collapsible%open]
====
.Datastores NFS como armazenamento principal para domínios de carga de trabalho VCF
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.Armazenamentos de dados iSCSI como armazenamento suplementar para domínios de gerenciamento VCF
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.NetApp com VMware Tanzu
[%collapsible%open]
====
O VMware Tanzu permite que os clientes implantem, administrem e gerenciem seu ambiente Kubernetes por meio do vSphere ou do VMware Cloud Foundation.  Este portfólio de produtos da VMware permite que o cliente gerencie todos os seus clusters Kubernetes relevantes a partir de um único plano de controle, escolhendo a edição do VMware Tanzu que melhor atende às suas necessidades.

Para obter mais informações sobre o VMware Tanzu, consulte o https://tanzu.vmware.com/tanzu["Visão geral do VMware Tanzu"^] .  Esta análise abrange casos de uso, adições disponíveis e muito mais sobre o VMware Tanzu.

.Como usar vVols com NetApp e VMware Tanzu Basic, parte 1
video::ZtbXeOJKhrc[youtube,width=360]
.Como usar vVols com NetApp e VMware Tanzu Basic, parte 2
video::FVRKjWH7AoE[youtube,width=360]
.Como usar vVols com NetApp e VMware Tanzu Basic, parte 3
video::Y-34SUtTTtU[youtube,width=360]
====
.Cloud Insights da NetApp Cloud
[%collapsible%open]
====
O NetApp Cloud Insights é uma plataforma abrangente de monitoramento e análise projetada para fornecer visibilidade e controle sobre sua infraestrutura local e na nuvem.

.NetApp Cloud Insights - Observabilidade para o Data Center Moderno
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====