---
sidebar: sidebar 
permalink: vmware/vmw-vcf-provision.html 
keywords: vmware, vcf, provision, principal, storage 
summary:  
---
= Provisione um ambiente VCF com ONTAP como a principal solução de armazenamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP é uma solução de storage primário ideal para o gerenciamento e os domínios de carga de trabalho do VMware Cloud Foundation (VCF). O ONTAP oferece alto desempenho, escalabilidade, gerenciamento de dados avançado e integração perfeita para melhorar a eficiência operacional e a proteção de dados.

Consulte as soluções a seguir para obter detalhes técnicos sobre o provisionamento de um ambiente VCF no domínio apropriado e com o protocolo apropriado.

* link:vmw-vcf-mgmt-principal-fc.html["Domínio de Gestão com FC"]
* link:vmw-vcf-mgmt-principal-nfs.html["Domínio de Gerenciamento com NFS"]
* link:vmw-vcf-viwld-principal-fc.html["Domínio de workload com FC"]
* link:vmw-vcf-viwld-principal-nfs.html["Domínio de workload com NFS"]

