---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= Use um armazenamento de dados NFS no ONTAP como armazenamento principal para o domínio de gerenciamento VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Neste caso de uso, descrevemos o procedimento para criar um datastore NFS no ONTAP como storage primário para o domínio de gerenciamento do VMware Cloud Foundation (VCF). Este procedimento resume os componentes necessários, as etapas de configuração e o processo de implantação.



[[introduction]]
== Introdução

Quando apropriado, faremos referência à documentação externa para os passos que devem ser executados em vCenter e mencionaremos os passos que são específicos para a parte de configuração de storage.

Se for necessário usar o datastore NFS 4.1 para o storage primário ou se estiver convertendo um ambiente vSphere existente baseado em NFS com o ONTAP, consulte link:vmw-vcf-mgmt-nfs.html["Convergir o ambiente vSphere (datastore NFS) para o domínio de gerenciamento VCF"].


NOTE: A versão 5.2 do VCF introduziu a capacidade de converter um ambiente vSphere 8 existente em um domínio de gerenciamento do VCF ou importá-lo como domínios de carga de trabalho do VCF VI. Antes dessa versão, o VMware vSAN era a única opção de storage primário para o domínio de gerenciamento do VCF. É recomendável implantar as VMs do controlador NSX em um datastore VMFS baseado em FC ou usar dois switches de rede para evitar ponto único de falha. Se essas opções não estiverem disponíveis, considere usar o vSAN para hospedar essas VMs.


NOTE: Esta solução é aplicável para plataformas ONTAP que suportam storage NFS, incluindo NetApp AFF, AFX e FAS.



[[prerequisites]]
== Pré-requisitos

Os seguintes componentes e configurações são usados neste cenário:

* Sistema de armazenamento NetApp com uma máquina virtual de armazenamento (SVM) configurada para permitir tráfego NFS.
* A interface lógica (LIF) foi criada na rede IP que transportará o tráfego NFS e está associada ao SVM.
* Um cluster vSphere com pelo menos 2 hosts vSphere.
* O datastore NFS está montado em um dos hosts vSphere com o mesmo servidor NFS e caminho de exportação que será usado para o domínio de gerenciamento.



NOTE: Ao implantar um domínio VCF, o VCF valida a conectividade com o servidor NFS. Isso é feito usando o adaptador de gerenciamento nos hosts vSphere antes que qualquer adaptador vmkernel adicional seja adicionado com o endereço IP do NFS. Portanto, é necessário garantir que 1) a rede de gerenciamento seja roteável para o servidor NFS ou 2) uma LIF para a rede de gerenciamento tenha sido adicionada à SVM que hospeda o volume do datastore NFS, para garantir que a validação possa prosseguir.

* Certifique-se de que a ferramenta ONTAP NFS VAAI esteja instalada em um dos hosts vSphere que pode ser selecionado como modelo para a imagem do cluster.
* Implante a ferramenta de instalação do VCF.


Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consulte link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentação do VMware Cloud Foundation"].



[[deployment-steps]]
== Etapas de implantação



[[management-domain-default-cluster]]
=== Domínio de Gerenciamento - Cluster Padrão

A ferramenta de instalação do VCF oferece suporte a VMFS em FC, datastores NFS v3 e vSAN para o domínio de gerenciamento. As etapas a seguir descrevem o procedimento para implantar um domínio de gerenciamento com um datastore baseado em NFSv3 no ONTAP como o storage principal.


NOTE: Valide ou ajuste o valor nConnect para o datastore NFS após a implantação.

Para obter mais informações sobre como usar um ambiente vSphere existente, consulte link:vmw-vcf-mgmt-nfs.html["Convergir o ambiente vSphere (datastore NFS) para o domínio de gerenciamento VCF"].



[[management-domain-additional-cluster]]
=== Domínio de Gerenciamento - Cluster Adicional

Para expandir o domínio de gerenciamento com um cluster adicional, consulte  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Adicionar um cluster SDDC a um domínio VCF"].

Em um nível mais alto, as etapas para adicionar um cluster adicional ao domínio de gerenciamento são as seguintes: * Certifique-se de que os hosts estejam comissionados e os pools de rede estejam configurados no vCenter. * O volume do datastore NFS deve estar provisionado no sistema de storage ONTAP e exportado para os hosts no cluster adicional. * Crie um novo cluster SDDC no domínio de gerenciamento no vCenter e siga o assistente para adicionar o cluster adicional ao domínio de gerenciamento.



[[additional-information]]
== Informações adicionais

Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consulte link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentação do VMware Cloud Foundation"].
