---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-mgmt-supp-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS no FC como armazenamento suplementar para domínios de gerenciamento e carga de trabalho VI usando ferramentas ONTAP para VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Neste cenário, demonstraremos como implantar o armazenamento de dados VMFS com backend Fibre Channel (FC) para domínios de gerenciamento e carga de trabalho utilizando ferramentas ONTAP .



== Benefícios do Fibre Channel

*Alto desempenho:* o FC fornece altas taxas de transferência de dados, tornando-o ideal para aplicações que exigem acesso rápido e confiável a grandes quantidades de dados.

*Baixa latência:* latência muito baixa, o que é crucial para aplicativos sensíveis ao desempenho, como bancos de dados e ambientes virtualizados.

*Confiabilidade:* As redes FC são conhecidas por sua robustez e confiabilidade, com recursos como redundância integrada e correção de erros.

*Largura de banda dedicada:* o FC fornece largura de banda dedicada para tráfego de armazenamento, reduzindo o risco de congestionamento da rede.

Para obter mais informações sobre o uso do Fibre Channel com sistemas de armazenamento NetApp , consulte https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisionamento SAN com FC"] .



== Visão geral do cenário

O armazenamento de dados suplementar do VCF é fornecido como parte das operações do dia 2 usando o vCenter.  Este cenário abrange as seguintes etapas de alto nível:

* Implantação de ferramentas ONTAP no domínio de gerenciamento
* Registrar servidores vCenter de carga de trabalho VI em ferramentas ONTAP
* Definir backend de armazenamento no plugin de ferramentas ONTAP para VMware vSphere
* Provisionar VMFS no transporte FC




== Pré-requisitos

Este cenário requer os seguintes componentes e configurações:

* Um sistema de armazenamento ONTAP com portas FC conectadas a switches FC.
* SVM criado com FC lifs.
* vSphere com HBAs FC conectados a switches FC.
* O zoneamento de iniciador-alvo único é configurado em switches FC.
+

NOTE: Use a interface lógica SVM FC na configuração de zona em vez de portas FC físicas em sistemas ONTAP .



A NetApp recomenda vários caminhos para LUNs FC.

Para obter informações completas sobre a configuração do Fibre Channel em sistemas de armazenamento ONTAP , consulte https://docs.netapp.com/us-en/ontap/san-management/index.html["Gerenciamento de armazenamento SAN"] na documentação do ONTAP 9.

Para obter mais informações sobre o uso do VMFS com sistemas de armazenamento ONTAP , consulte olink:vmw-vmfs-deploy.html["Guia de implantação para VMFS"] .



== Etapas de implantação para domínio de gerenciamento

Para implantar o ONTAP Tools e usá-lo para criar um armazenamento de dados VMFS no domínio de gerenciamento do VCF, conclua as seguintes etapas:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Implantar ferramentas ONTAP no domínio de gerenciamento"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definir backend de armazenamento usando a interface do cliente vSphere"]
* link: https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.htmlProvision VMFS no FC]




== Etapas de implantação para o domínio de carga de trabalho do VI

Para implantar o ONTAP Tools e usá-lo para criar um armazenamento de dados VMFS no domínio de carga de trabalho do VCF VI, conclua as seguintes etapas:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Registre a carga de trabalho VI vCenter para habilitar o plug-in vCenter"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definir backend de armazenamento usando a interface do cliente vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Provisionar VMFS no FC"]




== Informações adicionais

Para obter informações sobre como configurar sistemas de armazenamento ONTAP , consulte olink:https://docs.netapp.com/us-en/ontap["Documentação do ONTAP 9"] centro.

Para obter informações sobre como configurar o VCF, consultelink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentação do VMware Cloud Foundation"] .



== Demonstração em vídeo desta solução

.VMFS(FC) Datastore como armazenamento suplementar para domínio de gerenciamento VCF
video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto,width=360]