---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-automation.html 
keywords:  
summary:  
---
= Aprenda a usar as APIs ONTAP e VMware para administração
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP e VMware oferecem APIs para integração e automação perfeitas entre plataformas de armazenamento e virtualização.  Isso permite provisionamento, monitoramento e proteção de dados simplificados para melhorar a consistência do fluxo de trabalho.



== Introdução

A VMware fornece uma variedade de APIs que permitem aos administradores interagir programaticamente com vários produtos e serviços da VMware, aumentando a eficiência e a consistência nas operações.  Além disso, as APIs do NetApp ONTAP fornecem um conjunto robusto de ferramentas que permitem aos administradores automatizar, integrar e otimizar o gerenciamento de ambientes de armazenamento, especialmente em conjunto com cargas de trabalho do VMware.  Essas APIs facilitam a interação perfeita entre os sistemas de armazenamento ONTAP e o VMware, melhorando a eficiência, o desempenho e a proteção de dados.



== APIs baseadas em VMware

* *VMware vSphere API:* A vSphere API é uma API abrangente que permite aos administradores gerenciar e automatizar ambientes VMware vSphere.  Ele fornece acesso a uma ampla gama de recursos do vSphere, incluindo provisionamento, configuração, monitoramento e gerenciamento de ciclo de vida de máquinas virtuais.
* *VMware vCenter Server REST API:* A vCenter Server REST API fornece uma interface RESTful moderna para gerenciar o vCenter Server e seus componentes associados.  Simplifica a automação e a integração com outros sistemas e ferramentas.
* *VMware Cloud Foundation API:* As APIs do VMware Software-Defined Data Center (SDDC) fornecem acesso programático aos vários componentes e serviços dentro de um ambiente VMware SDDC.  Essas APIs permitem que administradores e desenvolvedores automatizem, gerenciem e integrem os diferentes aspectos do data center, incluindo serviços de computação, armazenamento, rede e gerenciamento.
* *VMware vSphere Storage APIs - Conscientização de armazenamento:* VASA é um conjunto de APIs que fornece integração de matrizes de armazenamento com o vCenter para gerenciamento e administração.  A arquitetura é baseada em vários componentes, incluindo o VASA Provider, que gerencia a comunicação entre o VMware vSphere e os sistemas de armazenamento.  Com o ONTAP, o provedor é implementado como parte das ONTAP tools for VMware vSphere.
* *APIs de armazenamento do VMware vSphere - Integração de matriz:* VAAI é um conjunto de APIs que permitem a comunicação entre hosts VMware vSphere ESXi e os dispositivos de armazenamento.  A API inclui um conjunto de operações primitivas usadas pelos hosts para descarregar operações de armazenamento para o array.  O VAAI pode fornecer melhorias significativas de desempenho para tarefas que exigem muito armazenamento.




== APIs baseadas em ONTAP

* * API REST do NetApp ONTAP :* A API REST do ONTAP fornece uma interface RESTful moderna para gerenciar sistemas de armazenamento ONTAP .  Ele simplifica a automação de tarefas de armazenamento, como provisionamento, monitoramento e configuração.  Ele permite fácil integração com o VMware vSphere e outras ferramentas de gerenciamento da VMware, possibilitando operações de armazenamento automatizadas diretamente de ambientes VMware.  Ele oferece suporte a uma ampla variedade de operações, desde gerenciamento básico de armazenamento até tarefas avançadas de proteção e replicação de dados, permitindo um gerenciamento de armazenamento escalável e flexível.
* * Ferramentas ONTAP para VMware vSphere:* As ONTAP tools for VMware vSphere são um conjunto de ferramentas para integrar o ONTAP e o vSphere.  Ele implementa a funcionalidade do provedor da estrutura da API VASA.  As ferramentas ONTAP também incluem o plug-in vCenter, um adaptador de replicação de armazenamento (SRA) para o VMware Site Recovery Manager e um servidor REST API que você pode usar para criar aplicativos de automação.




== Resumo

Em resumo, com as APIs ONTAP , os administradores podem criar scripts para a criação e configuração de datastores em ambientes VMware, garantindo um provisionamento de armazenamento rápido e consistente.  Além disso, eles podem automatizar a criação, o agendamento e a exclusão de instantâneos para máquinas virtuais VMware, fornecendo opções eficientes de proteção e recuperação de dados.  As APIs do SnapMirror facilitam a automação da configuração e do gerenciamento do relacionamento de replicação, garantindo soluções robustas de recuperação de desastres para cargas de trabalho do VMware.  Os administradores também podem implementar scripts para monitorar métricas de desempenho de armazenamento e acionar alertas ou ações automatizadas quando os limites de desempenho forem violados, garantindo o desempenho ideal de armazenamento para cargas de trabalho do VMware.  Ao integrar APIs ONTAP com APIs VMware, como as fornecidas pelo vSphere e vRealize, os administradores podem obter uma experiência de gerenciamento perfeita e altamente automatizada, melhorando a eficiência geral e a confiabilidade de sua infraestrutura virtualizada.
